server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      host: localhost
      database: catalog
      port: 27018
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  server:
    waity-time-in-ms-when-sync-empty: 0


  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

queue:
  serie:
    name: TestQueueSerie

message: registro up

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      circuitBreakers:
        enabled: true
    endpoint:
      health:
        show-details: always

resilience4j:
  circuitbreaker:
    instances:
      series:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
retry:
  instances:
    series:
      maxRetryAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - feign.FeignException$InternalServerError

