server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: catalogRoute
            uri: lb://catalog-service/
            predicates:
              - Path=/api/v1/catalog/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
