server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27018
  rabbitmq:
    username: guest
    passowrd: guest
    host: localhost
    port: 5672
management:
  tracing:
    sampling:
        probability: 1.0
logging:
  logging:
    pattern:
      level: "%5p [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%t] --- %c{1}.%M() : %m%n"
  level:
    org:
      springframework:
        web: DEBUG

queue:
  serie:
    name: TestQueueSerie

message: registro up

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
